Feature/order 주문생성시 Response 실응답과 swagger예시 맞춤
Gosrock/Ticket-Backend-22th pull request #64
Opened 2022-07-26 18:22 UTC by kim-wonjin

## 📝 PR Summary

주문생성시 Response 실응답과 swagger예시 맞춤
Response Dto로 수정

#### 🌲 Working Branch

Feature/order 

#### 🌲 TODOs

### Related Issues

#42

2022-07-26 18:24 UTC, ImNM commented
데브에서 한번 풀땡겨와주셔유 테스트 성공하게 만들어놨는디

2022-07-26 18:26 UTC, ImNM requested changes

2022-07-26 18:26 UTC, ImNM commented on src/orders/dtos/response-order.dto.ts
> +	  @Expose()
오~ 이거잘해놨는데~~ 굿굿

2022-07-26 18:26 UTC, ImNM commented on src/orders/dtos/response-order.dto.ts
> +	  @Expose()
근데 PickType 쓰시면 편해요

2022-07-26 18:31 UTC, ImNM commented
원진아 서비스레이어에서 디티오 클래스로 만들어줘야해
그래야 정상작동하는거임
https://github.com/typestack/class-transformer#plaintoclass
요런 메서드알아보시구

응답디티오에 중복 값들은
https://ganzicoder.tistory.com/159
요걸로 알아보셈

2022-07-26 18:49 UTC, ImNM commented
https://github.com/Gosrock/Ticket-Backend-22th/blob/feature/order/src/database/repositories/order.repository.ts#L40-L48

원진아그리고  오더정보가져올때 join 안적어줬어
이러면 유저정보 어드민 정보 안와

2022-07-27 06:17 UTC, kim-wonjin commented on src/orders/dtos/response-order.dto.ts
> +	  @Expose()
앗 넹

2022-07-27 06:24 UTC, kim-wonjin commented
1. 주문 생성 응답을 서비스레이어에서 디티오로 만들면,  슬랙이랑 네이버문자 함수에 파라미터로 넘겨줄때 만든 응답dto 넘겨주면 되나용?
2. 접근한 유저가 자기 주문목록을 조회하는 메소드에서 유저정보와 어드민 정보를 추가로 가져와야하나요? (join관련 얘기한 부분)
    그건 관리자페이지에서 주문목록 조회할때 넣으면 안되나?

2022-07-27 06:39 UTC, ImNM commented
> @kim-wonjin 
> 1. 주문 생성 응답을 서비스레이어에서 디티오로 만들면,  슬랙이랑 네이버문자 함수에 파라미터로 넘겨줄때 만든 응답dto 넘겨주면 되나용?
> 2. 접근한 유저가 자기 주문목록을 조회하는 메소드에서 유저정보와 어드민 정보를 추가로 가져와야하나요? (join관련 얘기한 부분)
>    그건 관리자페이지에서 주문목록 조회할때 넣으면 안되나?


주문 생성 응답 dto 에서 필요로하는 내용 ( 필드들을 )
생성자를 통해서 넘겨주시면 됩니다. 내용을 채워서 클래스 인스턴스로 만들면
클래스 인스턴스 --- (클래스 시리얼라이저 ) ---- 객체  ------ (클라이언트로 응답 ) ----- json 
으로 이루어지고
https://github.com/nestjs/nest/blob/master/packages/common/serializer/class-serializer.interceptor.ts#L61-L84
위에 소스가 클래스 시리얼라이저 에요
```javascript
 /**
   * Serializes responses that are non-null objects nor streamable files.
   */
  serialize(
    response: PlainLiteralObject | Array<PlainLiteralObject>,
    options: ClassTransformOptions,
  ): PlainLiteralObject | Array<PlainLiteralObject> {
    if (!isObject(response) || response instanceof StreamableFile) {
      return response;
    }
// 어레이 형인지 아닌지 조사해서 리턴
    return Array.isArray(response)
      ? response.map(item => this.transformToPlain(item, options))
      : this.transformToPlain(response, options);
  }

  transformToPlain(
    plainOrClass: any,
    options: ClassTransformOptions,
  ): PlainLiteralObject {
// 리터럴 객체 ( 생성자가 없는 순수 객체면 ) 그 순수 객체 그대로리턴
// 클래스 형태면 클래스를 객체로 바꾸면서 리턴
    return plainOrClass
      ? classTransformer.classToPlain(plainOrClass, options)
      : plainOrClass;
  }

```
 위방식때문에 현상태라면.
ticket entity 클래스를 리턴하는거라
지금 만든 dto랑 전혀 아무런 관계도없어요
운좋게 타입이랑 없는 정보가 맞아 떨어져서 리턴된거고

dto로 클래스를 만들고 생성자를 통해서 클래스 형태의 instance로 만드셔야지
`시리얼라이저에서` 클래스인스턴스인 객체를보고 class-transformer 를 통해서
expose 든 exclude든 리터럴 객체로 변환하는 과정을 거쳐서 정상 작동을합니다 

2. 이번은 뭐 ... 유저정보랑 어드민 정보 없애셔도됩니다.

2022-07-27 13:30 UTC, ImNM commented
@kim-wonjin  원진님 
dev에서 pull 땡겨와주실래요 
어제자 enum ticket 마이그레이션한거 반영이 안되어있어요

2022-07-27 13:34 UTC, ImNM requested changes

2022-07-27 13:34 UTC, ImNM commented on src/orders/orders.controller.ts
>    @ApiUnauthorizedResponse({
type : [ResponseOrderListDto]
로 만들어주세용

2022-07-27 13:34 UTC, ImNM commented on src/orders/dtos/response-order.dto.ts
> +	'ticketCount',
partialType은 옵셔널하게 필드를 뽑아오는거에유
pickType만 쓰시면 됩니다

2022-07-27 13:34 UTC, ImNM commented on src/orders/orders.service.ts
>  }
```javascript

 const orderList = await this.orderRepository.findAllByUserId(userId);
    return orderList.map(order => {
      return new ResponseOrderListDto(order));
    });;

```

이게 올바른 코드입니당...!
MAP 은 for문이 아니에유..

2022-07-27 13:39 UTC, ImNM commented on src/orders/dtos/response-order.dto.ts
> +  }
..... 왜 , 인가요 ;;;;;; 세미콜론 어디갔어유...ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

2022-07-27 13:39 UTC, kim-wonjin commented
엥 나 풀 땡겨서 마이그레이션 했는디 뭐지

2022-07-27 13:40 UTC, kim-wonjin commented
지금 풀 되어 있는 상태에여

2022-07-27 13:44 UTC, kim-wonjin commented on src/orders/dtos/response-order.dto.ts
> +  }
멍청코딩 죄송합니다.,,,,,,ㅋㅋㅋㅋㅋ

2022-07-27 13:47 UTC, kim-wonjin commented on src/orders/orders.controller.ts
>    @ApiUnauthorizedResponse({
그렇게 고치니까 스웨거 응답값 예시가 이상하게 나오는데요...?
[
   "string"
]
이렇게 돼용...

2022-07-27 13:48 UTC, ImNM commented
아 풀은 ㄱㅊ

2022-07-27 13:49 UTC, ImNM commented on src/orders/orders.service.ts
>  }
```javascript
async findAllByUserId(userId: number): Promise<ResponseOrderListDto[]> {
    const orderList = await this.orderRepository.findAllByUserId(userId);
    return plainToInstance(ResponseOrderListDto, orderList);
  }
```

만약에 ResponseOrderListDto 에있는 생성자 지우시면 
위 한줄로도 처리가능합니당

2022-07-27 13:50 UTC, ImNM commented
![무제](https://user-images.githubusercontent.com/13329304/181263791-ce41969b-c8f8-4852-84b6-e3294956b06e.jpg)
partialType 쓰시면 이렇게 되어요...
필요할때만 쓰세유...

2022-07-27 13:51 UTC, kim-wonjin commented on src/orders/orders.service.ts
>  }
오 넵넵

2022-07-27 14:03 UTC, ImNM commented
근데 orderListDto 따로둔거야?
리스트형은 orderDto[]
스웨거는
type : [orderDto]
로만들면됨
따로 orderListDto 만들필요가없음
@kim-wonjin

2022-07-27 14:14 UTC, ImNM commented on src/orders/orders.controller.ts
>    @ApiUnauthorizedResponse({
@kim-wonjin  아 밑에
isArray true 가 있군요 못봤네요 지송지송

2022-07-27 14:15 UTC, merged